### ISSUE TITLE
Duplicate changelogs are confusing

### ISSUE THREAD

**Issue by martey** [klen/django_markdown#19]
The README of the project points users to http://pythonhosted.org/django-markdown/changes.html in order to view the most recent changes, but this file only contains changes up to v0.1.0.

There is [a file called ChangeLog.txt in the root of the repository](https://github.com/klen/django_markdown/blob/2ab163db6128c521edbb07d7fcba19acffc16492/ChangeLog.txt), but the fact that it has a TXT extension means that Github does not display its ReStructuredText properly. It also contains the exact same information as [the changelog in the package's documentation](https://github.com/klen/django_markdown/blob/205476a2bf2ca92b2181af9baceef1db01c52fd2/docs/changes.rst).

I would suggest:
- deleting ChangeLog.txt, since it is duplicates already existing information and makes it more likely that it or changes.rst will fail to be updated, and
- either updating the documentation on pythonhosted.org or updating the README to point at the repository's changes.rst.

I can create a pull request for these changes if you would like.

**Comment by klen** [comment]
Fixed. Thanks.
