### ISSUE TITLE
Custom admin

### ISSUE THREAD

**Issue by sindresorhus** [klen/django_markdown#4]
I'm already using a custom admin. How can I assign the markdown widget directly to a model and have it show up in admin?

**Comment by klen** [comment]
You use MarkdownModelAdmin? When all textfield in your admin will be rendered with markdown widget.

Or you may use this construction:

class MyModelAdmin(admin.ModelAdmin):
    formfield_overrides = {
        models.TextField: {'widget': MarkdownWidget},
    }
